documents = [
	"100 Linux Tips and Tricks",
	"A.LIST.Publishing.Hacker.Disassembling.Uncovered.eBook-LiB",
	"A Buffer Overflow Study - Attacks and Defenses (2002)",
	"A Developers Guide to SQL Server 2005",
	"AIX Reference for Sun Solaris Administrators",
	"AJAX And PHP - Building Responsive Web Applications (2006)",
	"A Practical Guide To Linux Commands, Editors, And Shell Programming (2005)",
	"A Practical Guide To Red Hat Linux, 3rd Edition (2006)",
	"A Practical Guide To Video And Audio Compression (2005)",
	"APress - The Definitive Guide to MySQL, 2nd Ed - 2004 - (By Laxxuss)",
	"ASP.NET 2.0 All-In-One Desk Reference For Dummies (2006)",
	"ASP.NET 2.0 Cookbook, 2nd Edition (2005)",
	"ASP.NET 2.0 Demystified (2005)",
	"ASP.NET 2.0 Everyday Apps For Dummies (2006)",
	"ASP.NET 2.0 Illustrated (2006)",
	"ASP.NET 2.0 Instant Results (2006)",
	"ASP.NET 2.0 MVP Hacks And Tips (2006)",
	"ASP.NET 2.0 Unleashed (2006)",
	"ASP.NET 2.0 Visual Web Developer 2005 Express Edition Starter Kit (2006)",
	"ASP.NET 2.0 Website Programming - Problem-Design-Solution (2006)",
	"ASP.NET Bible (2002)",
	"ASP.NET Database Programming Weekend Crash Course (2002)",
	"ASP.NET In A Nutshell, 2nd Edition (2003)",
	"Absolute BSD - The Ultimate Guide To FreeBSD (2002)",
	"Absolute Beginner's Guide To Microsoft Windows XP, 2nd Edition (2005)",
	"Absolute Beginner's Guide to Wi-Fi Wireless Networking (2004)",
	"Absolute OpenBSD - UNIX For The Practical Paranoid (2003)",
	"A programmers introduction to VB.NET 2001",
	"CSS - The Definitive Guide, 3rd Edition (2006)",
	"CSS - The Missing Manual (2006)",
	"CSS Cookbook, 2nd Edition (2006)",
	"CSS Hacks and Filters - Making Cascading Stylesheets Work (2005)",
	"CSS Instant Results (2006)",
	"CSS Web Design for Dummies (2005)",
	"CSharp - Your Visual Blueprint For Building .NET Applications (2002)",
	"CSharp In A Nutshell, 2nd Edition (2003)",
	"CSharp Language Pocket Reference - 2002 [CHM]",
	"CSharp Precisely (2004)",
	"CSharp Threading Handbook (2004)",
	"Cyber.Forensics.eBook-EEn",
	"DNS And BIND, 5th Edition (2006)",
	"DNS In Action (2006)",
	"DNS On Windows Server 2003 (2003)",
	"DNS and BIND Cookbook",
	"Data Mining Concepts and Techniques",
	"Data Structures and Algorithms with Object-Oriented Design Patterns in Python (2004)",
	"Database Nation The Death of Privacy in the 21st Century 2000",
	"Database Programming with JDBC and Java 2nd Edition 2000",
	"Debian GNU-Linux Bible (2001)",
	"Debian Linux Cookbook - Tips And Techniques For Everyday Use",
	"Debian The Perfect Setup",
	"Deploying IPv6 Networks (2006)",
	"Deploying Windows 2000 with Support Tools",
	"Design and Performance of the OpenBSD Statefull Packet Filter - Slides",
	"Designer's Guide To Mac OS X Tiger (2006)",
	"Designing And Implementing Linux Firewalls And QoS (2006)",
	"Designing SQL Server 2000 Databases for Net Enterprise Servers",
	"Designing a Wireless Network",
	"Desktop Applications with Microsoft Visual Basic 6.0 MCSD Training Kit.70-176 1999",
	"Developing Games In Java (2003)",
	"Developing Java Beans",
	"Developing Microsoft Asp Net Server Controls Andponents (Microsoft Press 2003)(2)",
	"Developing Web Applications with Microsoft Visual Basic",
	"Digital Design with CPLD Applications and VHDL",
	"Digital Lighting and Rendering, 2nd Edition (2006)",
	"Digital Photography - Expert Techniques, 2nd Edition (2006)",
	"Digital Photography All-In-One Desk Reference For Dummies, 3rd Edition (2006)",
	"Digital Press - Oracle High Performance Tuning for 9i and 10g",
	"Disassembling Code - IDA Pro And SoftICE (2006)",
	"Distributed Applications with Microsoft Visual Basic 6.0 MS",
	"Documenting Oracle Databases Complete Oracle Database Schema Auditing 2003",
	"Dreamweaver 8 - The Missing Manual (2005)",
	"Dreamweaver 8 All-In-One Desk Reference For Dummies (2006)",
	"Dreamweaver 8 Design and Construction (2006)",
	"Dreamweaver 8 For Dummies (2006)",
	"Drive-By Wi-Fi Guide (2003)",
	"Ebook - Tcpip Network Administration (O'Reilly)",
	"Eclipse.A.Java.Developers.Guide",
	"Effective Enterprise Java (2004)",
	"Effective Use Of Microsoft Enterprise Library (2006)",
	"Embedded FreeBSD Cookbook (2002)",
	"Embedded Linux Primer - A Practical Real-World Approach (2006)",
	"Encryption In A Windows Environment - EFS File, 802.1x Wireless, IPSec Transport, And S-MIME Exchan",
	"Encyclopedia of Forensic Sciences (3 volumes) WW",
	"Enhancing Microsoft Content Management Server With ASP.NET 2.0 (2006)",
	"Enterprise.JavaBeans.3.0.5th.Edition.May.2006",
	"Enterprise JavaBeans, 4th Edition",
	"Enterprise JavaBeans 2.0, 3rd Ed ( Monson-Haefel)",
	"Essential ASP.NET With Examples In CSharp (2003)",
	"Essential CSharp 2.0 (2006)",
	"Essential PHP Security (2005)",
	"Everyday Scripting With Ruby (2006)",
	"Exceptional CPP - 47 Engineering Puzzles, Programming Problems, And Solutions (1999)",
	"Exceptional CPP Style - 40 New Engineering Puzzles, Programming Problems, And Solutions (2004)",
	"Expert CSharp 2005 Business Objects, 2nd Edition (2006)",
	"Expert Service-Oriented Architecture In CSharp 2005, 2nd Edition (2006)",
	"Expert VB 2005 Business Objects, 2nd Edition (2006)",
	"Exploiting Software - How To Break Code (2004)",
	"Exploring Macromedia Studio 8 (2005)",
	"Extending And Embedding PHP (2006)",
	"Extreme Exploits - Advanced Defenses Against Hardcore Hacks (2005)",
	"Fedora Linux (2006)",
	"Fiber Optics Technician's Manual 2nd Edition",
	"Firewall Fundamentals (2006)",
	"Firewall Policies And VPN Configurations (2006)",
	"Firewalls For Dummies, 2nd Edition (2003)",
	"Flash 8 - Projects For Learning Animation And Interactivity (2006)",
	"Flash 8 - The Missing Manual (2006)",
	"Flash 8 ActionScript Bible (2006)",
	"Flash 8 Cookbook (2006)",
	"Flash Hacks - 100 Industrial-Strength Tips and Tools (2004)",
	"Foundation ActionScript For Flash 8 (2006)",
	"Foundation Flash Applications For Mobile Devices (2006)",
	"Foundation XML For Flash (2005)",
	"Foundations Of Java For ABAP Programmers (2006)",
	"FreeBSD-MailServer-IMAP POP3",
	"FreeBSD-MailServer-Sendmail",
	"FreeBSD",
	"FreeBSD 6 Unleashed (2006)",
	"FreeBSD Developers' Handbook",
	"FreeBSD FAQ Book",
	"FreeBSD Handbook 5.1",
	"Fundamentals Of Computer Organization And Architecture (2005)",
	"GCC - The Complete Reference",
	"GDI+ Custom Controls With Visual CSharp 2005 (2006)",
	"Guerrilla Oracle 2003",
	"Guide To Assembly Language Programming In Linux (2005)",
	"HTML, XHTML, and CSS - Visual QuickStart Guide, 6th Edition (2006)",
	"HTML, XHTML, and CSS Bible, 3rd Edition (2004)",
	"HTML 4 For Dummies, 5th Edition (2005)",
	"HTML In 10 Simple Steps Or Less (2004)",
	"HTML Mastery - Semantics, Standards, And Styling (2006)",
	"HTML and XHTML - The Definitive Guide, 6th Edition (2006)",
	"Hack-Proof Your Wireless Network",
	"Hack Proofing Linux - A Guide To Open Source Security (2001)",
	"Hack Proofing Your Identity in the Information Age (Syngress-2002)",
	"Hack Proofing Your Network - Internet Tradecraft (Syngress-2000)",
	"Hack Proofing Your Web Applications (2001)",
	"Hack The Stack - Using Snort And Ethereal To Master The 8 Layers Of An Insecure Network (2006)",
	"Hacker Disassembling Uncovered (2003)",
	"Hacker Linux Uncovered (2005)",
	"Hackers Beware - Defending Your Network From The Wiley Hacker (2001)",
	"Hacking - Firewalls And Networks How To Hack Into Remote Computers",
	"Hacking Exposed - Network Security Secrets and Solutions, 2nd Edition (2001)",
	"Hacking Windows XP (2004)",
	"Hacking Wireless Networks For Dummies (2005)",
	"Hacknotes - Linux And Unix Security Portable Reference (2003)",
	"Hacknotes - Network Security Portable Reference (2003)",
	"Hacknotes - Windows Security Portable Reference (2003)",
	"Hardcore Windows XP (2005)",
	"Hardening Linux (2005)",
	"Hardening Windows, 2nd Edition (2005)",
	"Head First SQL",
	"High Performance MySQL (2004)",
	"Home Network Security Simplified (2006)",
	"Home Networking - The Missing Manual (2005)",
	"Home Networking Bible, 2nd Edition (2004)",
	"Home Networking for Dummies 3rd Edition",
	"Home Wireless Networking In A Snap (2006)",
	"Honeypots - Tracking Hackers (2002)",
	"Honeypots For Windows (2005)",
	"How Linux Works - What Every Super-User Should Know (2004)",
	"How Not To Program In CPP (2003)",
	"How To Cheat At Securing A Wireless Network (2006)",
	"How To Cheat At Windows System Administration Using Command Line Scripts (2006)",
	"How To Do Everything With PHP and MySQL (2005)",
	"How To Make People Like You In 90 Seconds Or Less",
	"How To Think Like A Computer Scientist-Learning With Python-2002",
	"IBM.Redbooks.Linux.Clustering.With.Csm.and.Gpfs.eBook-DDU",
	"IBM Oracle to DB2 Udb Conversion Guide Dec 2003",
	"IP Addressing And Subnetting - Including IPv6 (2000)",
	"IP In Wireless Networks (2003)",
	"IPSec - The New Security Standard For The Internet, Intranets, And Virtual Private Networks, 2nd Ed",
	"IPSec VPN Design (2005)",
	"IP Storage Networking - Straight To The Core (2003)",
	"IPsec Virtual Private Network Fundamentals (2006)",
	"IPv6 Essentials, 2nd Edition (2006)",
	"IPv6 Network Programming (2004)",
	"ITCertify - Oracle 9i 1Z0-031 Database Fundamentals I v15[1][1].0",
	"Idea To Image In Photoshop CS2 - Rick Sammon's Guide To Enhancing Your Digital Photographs (2006)",
	"Illustrated Mac OS X v.10.4 Tiger (2005)",
	"Illustrated TCP-IP - A Graphic Guide To The Protocol Suite (1999)",
	"ImageMagick Tricks - Web Image Effects From The Command Line And PHP (2006)",
	"Implementation and Usage of vLANs",
	"InDesign CS2 At Your Fingertips (2005)",
	"InDesign CS2 For Macintosh And Windows - Visual QuickStart Guide (2005)",
	"Incident Response and Computer Forensics 2nd ed. - C. Prosise, K. Mandia (2003) WW",
	"Inside CSharp, 2nd Edition (2002)",
	"Inside Microsoft SQL Server 2005 - T-SQL Programming (2006)",
	"Inside Microsoft Windows Server 2003 (2003)",
	"Inside Network Perimeter Security, 2nd Edition (2005)",
	"Insider Power Techniques For Microsoft Windows XP (2003)",
	"Intermediate Perl (2006)",
	"Internet Denial Of Service - Attack And Defense Mechanisms (2004)",
	"Internet Forensics - R. Jones (OReilly, 2005) WW",
	"Introduction To 80x86 Assembly Language And Computer Architecture (2001)",
	"Introduction To Computing And Programming With Java - A Multimedia Approach (2006)",
	"Introduction To Cryptography With Java Applets (2003)",
	"Introduction To SQL - Mastering The Relational Database Language, 4th Edition (2006)",
	"Intrusion Detection Systems with Snort - Prentice Hall - 2003",
	"Intrusion Prevention Fundamentals (2006)",
	"It's Never Done That Before - A Guide To Troubleshooting Windows XP (2006)",
	"Ivor Horton's Beginning Java 2, JDK 5 Edition (2005)",
	"Ivor Horton's Beginning Visual CPP 2005 (2006)",
	"J2EE Design Patterns (2003)",
	"J2Me In A Nutshell",
	"JBoss - A Developer's Notebook (2005)",
	"JBoss.at.Work.A.Practical.Guide.Oct.2005",
	"JBoss Administration (3.2.x Series) - 2003",
	"JBoss Administration and Development 2nd Ed (2002)",
	"JBoss Server Development with Eclipse",
	"JDBC Metadata, MySQL, And Oracle Recipes - A Problem-Solution Approach (2006)",
	"JSP - Java Server Pages 2nd Edition - 2002",
	"Jakarta Struts",
	"Jakarta Struts for Dummies",
	"JasperReports For Java Developers (2006)",
	"Java, Java, Java - Object-Oriented Problem Solving, 3rd Edition (2005)",
	"Java - A Beginner's Guide, 3rd Edition (2005)",
	"Java - How To Program, 6th Edition (2004)",
	"Java - Servlet Programming",
	"Java.Cookbook.2nd.Edition.Jun.30.2004.eBook-DDU",
	"Java.Enterprise.in.a.Nutshell.3rd.Edition.Nov.2005",
	"Java.I.O.2nd.Edition.May.2006",
	"Java.In.A.Nutshell.5th.Edition.Mar.2005.eBook-LiB",
	"Java.Management.Extension",
	"Java.RMI",
	"Java.Server.Pages.3rd.Edition.eBook-LiB",
	"Java 1.5 Tiger A Developers Notebook",
	"Java 2 Enterprise Edition 1.4 Bible (2003)",
	"Java 2 Network Security",
	"Java 3D Programming",
	"Java 6 Platform Revealed (2006)",
	"Java All-In-One Desk Reference For Dummies (2005)",
	"Java Concurrency In Practice (2006)",
	"Java Cookbook, 2nd Edition (2004)",
	"Java Cryptography",
	"Java Database Programming Bible (2002)",
	"Java Database Programming with JDBC",
	"Java EE And .NET Interoperability - Integration Strategies, Patterns, And Best Practices (2006)",
	"Java Enterprise In A Nutshell, 3rd Edition (2005)",
	"Java Extreme Programming Cookbook (2003)",
	"Java For Artists - The Art, Philosophy, And Science Of Object-Oriented Programming (2006)",
	"Java Generics And Collections (2006)",
	"Java IO, 2nd Edition (2006)",
	"Java In A Nutshell, 5th Edition (2005)",
	"Java Language Specification, 3rd Edition (2005)",
	"Java NIO",
	"Java Network Programming, 3rd Edition (2004)",
	"Java Open Source Programming (2004)",
	"Java Performance Tuning, 2nd Edition",
	"Java Persistence With Hibernate (2006)",
	"Java Programming with Oracle JDBC 2002",
	"Java Programming with Oracle ODBC 2002",
	"Java Puzzlers - Traps, Pitfalls, And Corner Cases (2005)",
	"JavaScript Bible, 5th Edition (2004)",
	"JavaScript Bible - Gold Edition (2001)",
	"JavaScript In 10 Simple Steps Or Less (2004)",
	"JavaScript Phrasebook - Essential Code And Commands (2006)",
	"JavaScript Programmer's Reference (2001)",
	"JavaScript and AJAX For The Web - Visual QuickStart Guide, 6th Edition (2006)",
	"JavaScript for Dummies 4th Edition",
	"JavaServer.Faces.eBook-DDU",
	"JavaServer Pages, 2nd Edition (2003)",
	"Java Servlet and JSP Cookbook (2004)",
	"Java Swing",
	"Java Threads (2004), 3Ed Ddu",
	"Java Virtual Machine",
	"Java Web Services (2002)",
	"Java Web Services Architecture (2003)",
	"Java Web Services In A Nutshell June 2003",
	"Java and SOAP",
	"Java and XML, 2nd Edition (2001)",
	"Java and XML Binding",
	"Java and XSLT",
	"John.Wiley.And.Sons.MySQL.Enterprise.Solutions.eBook-LiB",
	"John.Wiley.And.Sons.Red.Hat.Linux.9.Professional.Secrets.eBook-DDU",
	"John.Wiley.AndSons.Network.Performance.Toolkit.Using.Open.Source.Testing.Tools.eBook-LiB",
	"John.Wiley.and.Sons.Internet.Security.Cryptographic.Principles.Algorithms.and.Protocols.eBook-DDU",
	"John.Wiley.and.Sons.Malicious.Cryptography.Exposing.Cryptovirology.eBook-DDU",
	"John.Wiley.and.Sons.PHP5.and.MySQL.Bible.eBook",
	"John Wiley And Sons - Data Mining-Concepts Models Methods And Algorithms Ebook-Fos",
	"Just Java 2, 6th Edition (2004)",
	"Just Say No To Microsoft (2005)",
	"Killer Game Programming In Java (2005)",
	"Knoppix Hacks (2004)",
	"LPI Linux Certification In A Nutshell, 2nd Edition (2006)",
	"Learn To Program With CPP (2003)",
	"Learning.Java.3rd.edition.May.2005",
	"Learning.Python.2nd.Edition.eBook-LiB",
	"Learning CSharp 2005, 2nd Edition (2006)",
	"Learning Java, 3rd Edition (2005)",
	"Learning JavaScript (2006)",
	"Learning Oracle PL-SQL [O'Reilly, 524s, 2001r]",
	"Learning PHP and MySQL (2006)",
	"Learning Perl",
	"Learning Perl Objects, References, and Modules (2003)",
	"Learning Red Hat Enterprise Linux and Fedora, 4th Edition (2004)",
	"Learning Red Hat Linux, 3rd Edition (2003)",
	"Learning SQL On SQL Server 2005",
	"Learning The bash Shell, 2nd Edition (1998)",
	"Learning The vi Editor, 6th Edition (1998)",
	"Learning Unix For Mac OS X Panther (2003)",
	"Learning Visual Basic .NET 2003",
	"Learning Windows Server 2003, 2nd Edition (2006)",
	"Learning XML",
	"Learning the KORN Shell",
	"Learning the Unix Operating System",
	"Linux+ Certification Bible (2002)",
	"Linux.C++.Programming.HOWTO",
	"Linux.Cookbook.(2004).DDU",
	"Linux.Network.Administrators.Guide.3rd.edition.Feb.2005.eBook-LiB",
	"Linux.SED and AWK",
	"Linux.Server.Hacks.Volume.Two.Dec.2005",
	"Linux.Server.Security.2nd.edition.Feb.2005.eBook-LiB",
	"Linux.in.a.Nutshell.5th.Edition.Jul.2005",
	"Linux All-In-One Desk Reference For Dummies (2006)",
	"Linux Bible 2006 Edition (2006)",
	"Linux Bible RedHat",
	"Linux Command Directory",
	"Linux Cookbook (2004)",
	"Linux Debugging And Performance Tuning - Tips And Techniques (2005)",
	"Linux Desktop Garage (2005)",
	"Linux Desktop Hacks (2005)",
	"Linux Device Drivers, 2nd Edition (2001)",
	"Linux For Dummies, 7th Edition (2006)",
	"Linux For Non-Geeks - A Hands-On, Project-Based, Take-It-Slow Guidebook (2004)",
	"Linux For Programmers And Users (2006)",
	"Linux In A Nutshell, 4th Edition (2003)",
	"Linux Kernel Development, 2nd Edition (2005)",
	"Linux Network Administrator's Guide - Second Edition",
	"Linux Phrasebook (2006)",
	"Linux Poster (O'Reilly)",
	"Linux Power Tools (2003)",
	"Linux RedHat Cluster Manager InstallationAdministrationGuide",
	"Linux Security Cookbook (2003)",
	"Linux Server Hacks - 100 Industrial-Strength Tips and Tools (2003)",
	"Linux Shell Scripting Tutorial",
	"Linux Shell Scripting With Bash (2004)",
	"Linux Smart Homes For Dummies (2006)",
	"Linux Timesaving Techniques For Dummies (2004)",
	"Linux Toys II - 9 Cool New Projects For Home, Office, And Entertainment (2006)",
	"Linux Troubleshooting Bible (2004)",
	"Linux Troubleshooting For System Administrators And Power Users (2006)",
	"Linux Unwired (2004)",
	"Linux Unwired",
	"MCAD MCSD Visual Basic .net XML Web Services And Server Components Study Guide 2003",
	"MCSE Training Kit-Microsoft Windows XP Professional",
	"MIT Guide to Lockpicking",
	"MS Office 2k Visual Basic for Applications Fundamentals",
	"MS Press - Inside Microsoft SQL Server 2000 eBook",
	"MS Press - Inside Windows 2000, Third Edition",
	"MS Press- SQL Server 2000 Administrators Companion",
	"Mac.OS.X.Tiger.for.Unix.Geeks.Jun.2005.eBook-DDU",
	"Mac.OS.X.Tiger.in.a.Nutshell.Nov.2005",
	"MacBook For Dummies (2006)",
	"Mac OS X For Java Geeks (2003)",
	"Mac OS X For Unix Geeks (2003)",
	"Mac OS X Hacks - 100 Industrial-Strength Tips and Tools (2003)",
	"Mac OS X Internals - A Systems Approach (2006)",
	"Mac OS X Panther For Unix Geeks (2004)",
	"Mac OS X Power Tools (2003)",
	"Mac OS X Tiger Timesaving Techniques For Dummies (2005)",
	"Mac OS X Tiger Timesaving Techniques for Dummies",
	"Mac mini Hacks and Mods for Dummies",
	"Macromedia Dreamweaver 8 (2006)",
	"Macromedia Dreamweaver 8 For Windows And Macintosh - Visual QuickStart Guide (2005)",
	"Macromedia Dreamweaver 8 Recipes (2005)",
	"Macromedia Dreamweaver 8 Unleashed (2005)",
	"Macromedia Dreamweaver MX Bible",
	"Macromedia Fireworks 8 - Training From The Source (2005)",
	"Macromedia Flash 8 - A Tutorial Guide (2005)",
	"Macromedia Flash 8 - Training From The Source (2005)",
	"Macromedia Flash 8 ActionScript - Training From The Source (2006)",
	"Macromedia Flash 8 Bible (2006)",
	"Macromedia Flash 8 For Dummies (2006)",
	"Macromedia Flash 8 For Windows And Macintosh - Visual QuickStart Guide (2005)",
	"Macromedia Flash MX Advanced For Windows And Macintosh",
	"Macromedia Flash Professional 8 Unleashed (2005)",
	"Macromedia Studio 8 - Training From The Source (2006)",
	"Macromedia Studio 8 All-In-One Desk Reference For Dummies (2006)",
	"Macromedia Studio MX 2004 All-in-One Desk Reference for Dummies",
	"Macs On The Go - Mobile Computing Guide (2006)",
	"Macs for Dummies 8th Edition",
	"Making Use Of Python (2002)",
	"Malware - Fighting Malicious Code (2003)",
	"Managing Cisco Network Security",
	"Managing Security With Snort And Ids Tools - 1St",
	"Managing and Using MySQL 2nd ed",
	"Manning.Publications.wxPython.in.Action.Mar.2006",
	"Marco.Tabini.and.Associates.PHP.Architects.Guide.to.PHP.Security.Sep.2005",
	"Mastering FreeBSD And OpenBSD Security (2005)",
	"Mastering IPTables",
	"Mastering Microsoft Exchange Server 2003 (2003)",
	"Mastering Microsoft Windows Server 2003 (2003)",
	"Mastering Microsoft Windows XP Registry (2002)",
	"Mastering MySQL 4 (2003)",
	"Mastering Oracle SQL 2nd ed 2004",
	"Mastering Visual Basic .NET (2002)",
	"Mastering Web Development With Microsoft Visual Studio 2005 (2005)",
	"Mastering Windows Network Forensics and Investigation (Sybex, 2007) WW",
	"Mastering phpMyAdmin For Effective MySQL Management, 3rd Edition (2006)",
	"Maximum Security - A Hacker's Guide To Protecting You",
	"McGraw-Hill - MySQL - Essential Skills - 2004",
	"McGraw-Hill - RSA Security - Official Guide to Cryptography - fly",
	"McGraw-Hill - Windows Server 2003. The Complete Reference",
	"McGraw.Hill.-.Oracle.Database.10g..High.Availablity.with.RAC.Flashback.and.Data.Guard",
	"McGraw.Hill.HackNotes.Linux.and.Unix.Security.Portable.Reference.eBook-DDU",
	"McGraw.Hill.RHCE.Red.Hat.Certified.Engineer.Linux.Study.Guide.Exam.RH302.4ED.Mar.2004.eBook-DDU",
	"McGraw.Hill.Red.Hat.The.Complete.Reference.Enterprise.Linux.and.Fedora.Edition.eBook-DDU",
	"McGraw Hill - Oracle Database 10g, A Beginner's Guide",
	"McGrawHill-Oracle Database 10g New Features",
	"McGraw Hill Hacking Exposed Web 2.0 December 2007",
	"Memory Management - Algorithms And Implementation In C-C++ (2002)",
	"Metasploit.Toolkit.for.Penetration.Testing.Exploit.Development.and.Vulnerability.Research.Sep.2007",
	"Microsoft CSharp Programming For The Absolute Beginner (2002)",
	"Microsoft Encyclopedia Of Security (2003)",
	"Microsoft Exchange Server 2003 Advanced Administration (2006)",
	"Microsoft Exchange Server 2003 Unleashed (2003)",
	"Microsoft IIS 6.0 - Administrator's Pocket Consultant (2003)",
	"Microsoft Internet Security And Acceleration (ISA) Server 2004 Administrator's Pocket Consultant",
	"Microsoft SQL Server 2005 Administrator's Companion (2006)",
	"Microsoft SQL Server 2005 Express Edition For Dummies (2006)",
	"Microsoft SQL Server 2005 For Dummies (2006)",
	"Microsoft SQL Server 2005 Integration Services (2006)",
	"Microsoft SQL Server 2005 Reporting Services for Dummies",
	"Microsoft SQL Server 2005 Stored Procedure Programming In T-SQL and .NET, 3rd Edition (2006)",
	"Microsoft Small Business Server 2003 Unleashed (2005)",
	"Microsoft Visual Basic 2005 Express Edition - Build a Program Now",
	"Microsoft Visual Basic 2005 Express Edition Programming For The Absolute Beginner (2006)",
	"Microsoft Visual Basic 2005 Step By Step (2006)",
	"Microsoft Visual CPP 2005 Express Edition Programming For The Absolute Beginner (2006)",
	"Microsoft Visual CSharp 2005 Step-By-Step (2005)",
	"Microsoft Windows Internals - Microsoft Windows Server 2003, Windows XP, and Windows 2000, 4th Edit",
	"Microsoft Windows Registry Guide, 2nd Edition (2005)",
	"Microsoft Windows Scripting Self-Paced Learning Guide (2004)",
	"Microsoft Windows Scripting Self Paced Learning Guide (2004) [SAMPLE FILES]",
	"Microsoft Windows Security Inside Out (2003)",
	"Microsoft Windows Server 2003 - The Complete Reference (2003)",
	"Microsoft Windows Server 2003",
	"Microsoft Windows Server 2003 Administrator's Companion, 2nd Edition (2006)",
	"Microsoft Windows Server 2003 Administrator's Pocket Consultant (2003)",
	"Microsoft Windows Server 2003 Deployment Kit - Automating and Customizing Installations",
	"Microsoft Windows Server 2003 For Dummies (2003)",
	"Microsoft Windows Server 2003 In A Nutshell (2003)",
	"Microsoft Windows Server 2003 Inside Out (2004)",
	"Microsoft Windows Server 2003 Insider Solutions (2003)",
	"Microsoft Windows Server 2003 Security Guide (2003)",
	"Microsoft Windows Server 2003 Unleashed - R2 Edition (2006)",
	"Microsoft Windows Server 2003 Weekend Crash Course (2003)",
	"Microsoft Windows Server Cookbook (2005)",
	"Microsoft Windows Small Business Server 2003 Administrator's Companion (2004)",
	"Microsoft Windows Vista - Visual QuickStart Guide (2006)",
	"Microsoft Windows XP Bible (2001)",
	"Microsoft Windows XP For Power Users (2004)",
	"Microsoft Windows XP Gigabook For Dummies (2004)",
	"Microsoft Windows XP Inside Out, 2nd Edition (2005)",
	"Microsoft Windows XP Networking Inside Out (2003)",
	"Microsoft Windows XP Professional - The Missing Manual (2003)",
	"Microsoft Windows XP Professional",
	"Microsoft Windows XP Registry Guide (2002)",
	"Minimal Perl For UNIX And Linux People (2005)",
	"Mission Critical! Windows 2000 Server Administration",
	"Mit_Lock_Guide",
	"Modeling Derivatives In CPP (2005)",
	"Modern CPP Design - Generic Programming and Design Patterns Applied (2001)",
	"More Exceptional CPP - 40 New Engineering Puzzles, Programming Problems, And Solutions (2001)",
	"Moving To Ubuntu Linux (2006)",
	"MySQL - Essential Skills (2004)",
	"MySQL - Visual QuickStart Guide, 2nd Edition (2006)",
	"MySQL.Press.MySQL.5.Certification.Study.Guide.2nd.Edition.Aug.2005.eBook-DDU",
	"MySQL.Press.MySQL.Administrators.Guide.and.Language.Reference.2nd.Edition.Apr.2006",
	"MySQL.Press.MySQL.Database.Design.and.Tuning.Jun.2005.eBook-DDU",
	"MySQL.Stored.Procedure.Programming.Mar.2006",
	"MySQL Administrator's Guide And Language Reference, 2nd Edition (2006)",
	"MySQL Certification Study Guide (2004)",
	"MySQL Cookbook (2002)",
	"MySQL Enterprise Solutions",
	"MySQL PHP Database Applications 2nd Ed 2004",
	"MySQL Pocket Reference (2003)",
	"MySQL Press MySQL Administrators Guide 2004",
	"MySQL Tutorial (2003)",
	"MySQL and Java Developers Guide",
	"Network Programming For Microsoft Windows, 2nd Edition (2002)",
	"Network Programming with Perl",
	"Network Security Assessment - From Vulnerability To Patch (2006)",
	"Network Security Hacks - 100 Industrial-Strength Tips and Tools (2004)",
	"Network Security Hacks - Tips and Tools For Protecting Your Privacy, 2nd Edition (2006)",
	"Network Security Tools (2005)",
	"Network Security With OpenSSL (2002)",
	"Network Troubleshooting Tools",
	"Network Tutorial, 5th Edition (2003)",
	"Networking All-In-One Desk Reference For Dummies, 2nd Edition (2005)",
	"Networking And Online Games (2006)",
	"Networking for Dummies 7th Edition",
	"New Riders - Advanced Linux Programming",
	"New Riders - Inside Linux",
	"New Riders - Jython for Java Programmers",
	"New Riders - PHP Functions Essential Reference",
	"New Riders - PostgreSQL Essential Reference",
	"New Riders - Web Application Development With PHP4",
	"New Riders - XML and PHP",
	"Next-Generation Network Services (2005)",
	"No.Starch.Press.How.Linux.Works.What.Every.Super.User.Should.Know.eBook-LiB",
	"No.Starch.Press.Linux.Enterprise.Cluster",
	"No Starch - Linux Cook Book-1.2",
	"No Starch Press - Absolute BSD. The Ultimate Guide to FreeBS",
	"Novell.Press.Linux.Firewalls.3rd.Edition.Sep.2005",
	"Novell.Press.Novell.Certified.Linux.Engineer.Novell.CLE.Study.Guide.Oct.2004.eBook-DDU",
	"Novell.Press.Novell.Linux.Certification.Practicum.Lab.Manual.Oct.2005.eBook-DDU",
	"O'Reilly - Postfix The Definitive Guide",
	"OCA Oracle 10g Administration I Study Guide 1Z0-042 2005",
	"OCP Oracle Database 10g New Features for Administrators 2004",
	"OOP with Microsoft Visual Basic .NET and Microsoft Visual C Sharp Step By Step 2002",
	"OReilly - Secure Programming Cookbook for C and CPP",
	"OReilly.Automating.System.Administration.with.Perl",
	"OReilly.bash.Cookbook.May.2007",
	"OS X For Hackers At Heart (2005)",
	"Object-Oriented PHP - Concepts, Techniques, And Code (2006)",
	"Object-Oriented Programming with Visual Basic.NET 2003",
	"Objective-C Pocket Reference (2002)",
	"OpenGL Distilled (2006)",
	"OpenGL Shading Language, 2nd Edition (2006)",
	"OpenOffice.org for Dummies",
	"Open Source Development With CVS, 3rd Edition (2003)",
	"Open Source For The Enterprise (2005)",
	"Open Source Network Administration (2003)",
	"Open Sources, Voices from the Open Source Revolution",
	"Open Sources 2.0 (2005)",
	"OpenVPN - Building And Integrating Virtual Private Networks (2006)",
	"Operating Systems - Design and Implementation, 3rd Edition (2006)",
	"Optimizing CPP (1999)",
	"Oracle - Advanced Programming With Packages",
	"Oracle - Oracle Built In Packages",
	"Oracle.Essentials.Oracle.Database.10g.3rd.Edition.eBook-LiB",
	"Oracle.PL.SQL.for.DBAs.Oct.2005",
	"Oracle4pros",
	"Oracle 8i - The Complete Reference (2000)",
	"Oracle 8i Interal Service 1999",
	"Oracle 9i - The Complete Reference (2002)",
	"Oracle 9i DBA JumpStart 2003",
	"Oracle 9i R2 Data Warehousing 2003",
	"Oracle 10G By Examples 2004",
	"Oracle 10g 2Day Training 2003",
	"Oracle 11i E-Business Suite From The Front Lines 2004",
	"Oracle Application Server 10g Administration Handbook 2004",
	"Oracle Application Server 10g Essentials 2004",
	"Oracle Applications DBA Field Guide (2006)",
	"Oracle DBA Checklists Pocket Reference",
	"Oracle DBA Guide to Data Warehousing and Star Schemas 2003",
	"Oracle DBA Made Simple Oracle Database Administration Techniques 2003",
	"Oracle DBA SQL Quick Reference 2003",
	"Oracle DBA Scripting Quick Reference 2004",
	"Oracle Data Warehouse Management 2003",
	"Oracle Database 10G - Automatic Sga Memory Management",
	"Oracle Database 10G - The Complete Reference 2004",
	"Oracle Database 10g, A Beginner's Guide",
	"Oracle Database 10g - DBA",
	"Oracle Database 10g - New Features",
	"Oracle Database 10g - Proactive Space and Schema Object Management 2003",
	"Oracle Database 10g - SQLAccess Advisor",
	"Oracle Database 10g High Availability with RAC Flashback and Data Guard 2004",
	"Oracle Database 10g New Features",
	"Oracle Database 10g SQL 2004",
	"Oracle Database 10g XML and SQL Design Build and Manage XML Applications in Java C C++ and PL SQL 2",
	"Oracle Database Foundations 2004",
	"Oracle Distributed Systems 1999",
	"Oracle Essentials Oracle Database 10g 3rd ed 2004",
	"Oracle High Performance Tuning for 9i and 10g 2004",
	"Oracle Index Management Secrets Top Oracle Experts Discuss Index Management Techniques 2003",
	"Oracle Language Pocket Reference",
	"Oracle Net8 Configuration and Troubleshooting 2001",
	"Oracle PL-SQL Best Practices (2001)",
	"Oracle PL-SQL Built-ins Pocket Reference",
	"Oracle PL-SQL Language Pocket Reference, 2nd Edition (2003)",
	"Oracle PL SQL Best Practices 2001",
	"Oracle PL SQL By Example 3rd Ed 2004",
	"Oracle PLSQL Interactive Workbook, 2nd ed 2003",
	"Oracle PL SQL Language Pocket Reference 2nd ed 2003",
	"Oracle PL SQL Programming",
	"Oracle PLSQL Programming Guide to Oracle 8i Features 1999",
	"Oracle Press - 0072231300 - Effective Oracle Database 10g Security by Design - fly",
	"Oracle RAC 10g Best Practices",
	"Oracle RMAN Pocket Reference 2001",
	"Oracle Real Application Clusters 2004",
	"Oracle Regular Expressions Pocket Reference 2003",
	"Oracle SQL Internals Handbook 2003",
	"Oracle SQL Plus Pocket Reference 2nd ed 2002",
	"Oracle SQL The Essential Reference 2000",
	"Oracle SQL Tuning Pocket Reference 2002",
	"Oracle Security 1998",
	"Oracle Space Management Handbook 2003",
	"Oracle Wait Interface A Practical Guide to Performance Diagnostics and Tuning 2004",
	"Oracle Web Applications PLSQL Developer's Introduction 1999",
	"Oracle XSQL 2003",
	"Oracle sql loader 2001",
	"Over-The-Road Wireless For Dummies (2006)",
	"PGP and GPG - Email For The Practical Paranoid (2006)",
	"PHP.Hacks.Tips.and.Tools.For.Creating.Dynamic.Websites.Dec.2005.HAPPY.NEW.YEAR",
	"PHP.in.a.Nutshell.Oct.2005",
	"PHP5 And MySQL Bible (2004)",
	"PHP 5 In Practice (2006)",
	"PHP5 Recipes - A Problem-Solution Approach (2005)",
	"PHP 5 for Dummies",
	"PHP Cookbook, 2nd Edition (2006)",
	"PHP Game Programming (2004)",
	"PHP Pocket Reference 2nd Edition",
	"PHP Programming With PEAR (2006)",
	"PHP Solutions - Dynamic Web Design Made Easy (2006)",
	"PHPUnit.Pocket.Guide.Sep.2005",
	"PHP and MySQL Everyday Apps for Dummies",
	"PHP and MySQL For Dummies, 2nd Edition (2004)",
	"Paint Shop Pro 8 for Dummies",
	"Paint Shop Pro 9 For Dummies (2005)",
	"Paraglyph Press - Windows Admin Scripting Little Black Book, Second Edition",
	"Peachpit.Press.UNIX.3rd.Edition.Visual.QuickStart.Guide.Aug.2006",
	"Peachpit.Press.Unix.for.Mac.OS.X.10.4.Tiger.Visual.QuickPro.Guide.2nd.Edition.Sep.2005",
	"Peachpit Press - PHP for the World Wide Web Visual Quick Start Guide",
	"Peer-To-Peer - Harnessing The Power Of Disruptive Technologies (2001)",
	"Peer-To-Peer With VB .NET (2003)",
	"Penetration Tester's Open Source Toolkit (2005)",
	"Perl - Perl For Sysadmins",
	"Perl.Hacks.Tips.and.Tools.for.Programming.Debugging.and.Surviving.May.2006",
	"Perl 6 Essentials",
	"Perl Best Practices (2005)",
	"Perl Cookbook",
	"Perl Hacks - Tips And Tools For Programming Debugging And Surviving (2006)",
	"Perl Medic - Transforming Legacy Code (2004)",
	"Perl and XML",
	"Perl for Oracle DBAs 2002",
	"Photoshop CS2 - Before and After Makeovers (2006)",
	"Photoshop CS2 All-in-One Desk Reference for Dummies",
	"Photoshop CS2 For Dummies (2005)",
	"Photoshop CS Timesaving Techniques For Dummies (2004)",
	"Photoshop Elements 4 for Dummies",
	"Photoshop Finishing Touches (2006)",
	"PostgreSQL - Introduction And Concepts (2001)",
	"PostgreSQL - The Comprehensive Guide, 2nd Edition (2005)",
	"Practical Business Intelligence With SQL Server 2005 (2006)",
	"Practical CPP Programming",
	"Practical C Programming, 3rd Edition (1999)",
	"Practical FPGA Programming In C (2005)",
	"Practical Mod Perl",
	"Practical PostgreSQL 2001",
	"Practical Study Remote Access (Cisco-December 22, 2003)",
	"Practical Unix and Internet Security, 3rd Edition (2003)",
	"Pragmatic.Bookshelf.Best.of.Ruby.Quiz.Mar.2006",
	"Pragmatic.Bookshelf.Enterprise.Integration.with.Ruby.Apr.2006",
	"Premier - PHP Fast And Easy Web Development 2nd Edition",
	"Premier.Press.Python.Programming.for.the.Absolute.Beginner.eBook-LiB",
	"Premier Press - Administering And Securing The Apache Server - 2002 [CHM]",
	"Prentice.Hall.Java.How.to.Program.6th.Edition.Aug.2004.INTERNAL",
	"Prentice.Hall.Java.Java.Java.Object.Oriented.Problem.Solving.3rd.Edition.Dec.2005",
	"Prentice.Hall.Linux.for.Programmers.and.Users.Feb.2006",
	"Prentice.Hall.PTR.A.Practical.Guide.to.Red.Hat.Linux.Fedora.Core.and.Red.Hat.Enterprise.Linux.3rd.E",
	"Prentice.Hall.PTR.Embedded.Linux.Primer.A.Practical.Real.World.Approach.Sep.2006",
	"Prentice.Hall.PTR.Internet.Denial.of.Service.Attack.and.Defense.Mechanisms.Dec.2004.eBook-DDU",
	"Prentice.Hall.PTR.Linux.Patch.Management.Keeping.Linux.Systems.Up.To.Date.Jan.2006",
	"Prentice.Hall.PTR.Linux.Quick.Fix.Notebook.Mar.2005",
	"Prentice.Hall.PTR.Linux.Troubleshooting.for.System.Administrators.and.Power.Users.Apr.2006",
	"Prentice.Hall.PTR.Open.Source.Security.Tools.Practical.Guide.to.Security.Applications.Jul.2004.eBook",
	"Prentice.Hall.PTR.Oracle.DBA.Scripting.Quick.Reference.Apr.2004.eBook-DDU",
	"Prentice.Hall.PTR.PHP.5.Power.Programming.Oct.2004.eBook-LiB",
	"Prentice.Hall.PTR.Performance.Tuning.for.Linux.Servers.May.2005.eBook-BBL",
	"Prentice.Hall.PTR.SELinux.by.Example.Using.Security.Enhanced.Linux.Jul.2006",
	"Prentice.Hall.PTR.Self.Service.Linux.Mastering.the.Art.of.Problem.Determination.Sep.2005",
	"Prentice.Hall.PTR.Solaris.Performance.and.Tools.Jul.2006",
	"Prentice.Hall.PTR.The.Linux.Kernel.Primer.A.Top.Down.Approach.for.x86.and.PowerPC.Architectures.Sep",
	"Prentice.Hall.PTR.The.Official.Ubuntu.Book.Aug.2006",
	"Prentice.Hall.PTR.Troubleshooting.Linux.Firewalls.Dec.2004.eBook-LiB",
	"Prentice.Hall.PTR.UNIX.to.Linux.Porting.A.Comprehensive.Reference.Apr.2006",
	"Prentice.Linux.On.The.Mainframe.eBook-LiB",
	"Prentice.Oracle.DBA.Guide.To.Data.Warehousing.And.Star.Schemas.eBook-LiB",
	"Prentice.Oracle.DBA.SQL.Quick.Reference.eBook-LiB",
	"Prentice.Oracle.PL.SQL.By.Example.3rd.Edition-LiB",
	"Prentice.Programming.Oracle.Triggers.And.Stored.Procedures.3rd.Edition.eBook-LiB",
	"Prentice.Technical.Java.Developing.Scientific.And.Engineering.Applications.eBook-LiB",
	"Prentice.Unix.Systems.Programming.Communication.Concurrency.And.Threads.eBook-LiB",
	"Prentice Hall - Linux Desk Reference, 2nd Edition",
	"Prentice Hall - The Art Of Unix Programming (Eric Raymond) - 2003 - (By Laxxuss)",
	"Prentice Hall - UNIX Fault Management A Guide For System Administration",
	"Prentice Hall - UNIX Shells by Example, Third Edition",
	"Prentice Hall - UNIX User's Handbook 2nd Edition",
	"Principles Of Computer Architecture (1999)",
	"Pro .NET 2.0 Code And Design Standards In CSharp, 3rd Edition (2006)",
	"Pro .NET 2.0 Windows Forms And Custom Controls In VB 2005 (2006)",
	"Pro ASP.NET 2.0 In CSharp 2005 (2005)",
	"Pro ASP.NET 2.0 In VB 2005, Special Edition (2006)",
	"Pro ASP.NET 2.0 Website Programming (2005)",
	"Pro Apache Ant (2005)",
	"Pro Apache XML (2006)",
	"Pro CSharp And The .NET 2.0 Platform, 3rd Edition (2005)",
	"Pro DNS And BIND (2005)",
	"Pro EJB 3 - Java Persistence API (2006)",
	"Pro JSF And Ajax - Building Rich Internet Components (2006)",
	"Pro Java EE 5 Performance Management And Optimization (2006)",
	"Pro Java ME MMAPI - Mobile Media API For Java Micro Edition (2006)",
	"Pro JavaScript Techniques (2006)",
	"Pro OpenSSH (2005)",
	"Pro SQL Server 2005 (2006)",
	"Pro SQL Server 2005 Reporting Services (2006)",
	"Pro VB 2005 And The .NET 2.0 Platform, 2nd Edition (2006)",
	"Pro Visual CPP-CLI And The .NET 2.0 Platform (2006)",
	"Pro Windows Small Business Server 2003 (2006)",
	"Producing.Open.Source.Software.Oct.2005.eBook-DDU",
	"Professional ASP.NET 2.0 (2006)",
	"Professional Apache Tomcat",
	"Professional Assembly Language (2005)",
	"Professional CPP (2005)",
	"Professional CSharp, 3rd Edition (2004)",
	"Professional CSharp 2005 (2005)",
	"Professional Java, JDK 5 Edition (2005)",
	"Professional Java, JDK 6 Edition (2007)",
	"Professional Java Development With The Spring Framework (2005)",
	"Professional JavaScript For Web Developers (2005)",
	"Professional Java User Interfaces (2006)",
	"Professional Oracle Programming (2005)",
	"Professional Rootkits",
	"Professional SQL Server 2005 Integration Services (2006)",
	"Professional SQL Server 2005 Reporting Services (2006)",
	"Professional SQL Server 2005 XML (2006)",
	"Professional VB 2005 (2006)",
	"Professional Visual Basic 5.0 Business Objects 1997",
	"Professional Visual Basic 6 Business Objects 2003",
	"Professional Visual Basic 6 Code 2002",
	"Professional Visual Basic 6 Databases 2003",
	"Professional Visual Basic 6 MTS Programming 2003",
	"Professional Visual Basic 6 Project Management 2003",
	"Professional Visual Basic 6 Web Programming 2003",
	"Professional Visual Studio 2005 Team System (2006)",
	"Professional Web APIs With PHP (2006)",
	"Programming Applications For Microsoft Windows, 4th Edition (1999)",
	"Programming CSharp, 4th Edition (2005)",
	"Programming Embedded Systems - With C And GNU Development Tools, 2nd Edition (2006)",
	"Programming Embedded Systems In C And CPP (1999)",
	"Programming Jakarta Struts (O'Reilly)",
	"Programming Linux Games (2001)",
	"Programming Microsoft Visual Basic 2005 - The Language (2006)",
	"Programming Microsoft Visual CSharp 2005 - The Language (2006)",
	"Programming Microsoft Windows With CSharp (2002)",
	"Programming Oracle Triggers And Stored Procedures 3rd ed 2004",
	"Programming PHP, 2nd Edition (2006)",
	"Programming Python, 3rd Edition (2006)",
	"Programming Ruby, 2nd Edition (2005)",
	"Programming Ruby - The Pragmatic Programmer's Guide",
	"Programming SQL Server 2005",
	"Programming The Windows Driver Model, 2nd Edition (2003)",
	"Programming The Windows Driver Model, 2nd Edition (2003) [SAMPLE FILES]",
	"Programming VB .NET 2002",
	"Programming Visual Basic .NET (2002)",
	"Programming Visual Basic for Palm OS 2002",
	"Programming With Microsoft Visual CPP .NET, 6th Edition (2003)",
	"Programming the Perl DBI",
	"Python 2.1 Bible",
	"Python Cookbook 2nd Edition Jun 2005 Ebook-Lib",
	"Python In A Nutshell, 2nd Edition (2006)",
	"Python Phrasebook (2006)",
	"Python Pocket Reference, 2nd Ed 2001",
	"Python Programming on Win32",
	"Python Programming with the JavaT Class Libraries - Addison Wesley - 2002",
	"Python Standard Library",
	"Que - Linux Socket Programming By Example - fly",
	"Que - MySQL and PHP from Scratch",
	"Que - Special Edition Using Linux 4th Edition",
	"Que - The Concise Guide to DNS and BIND",
	"Que - UNIX Hints Hacks",
	"Que.CCNA.Practice.Questions.Exam.Cram.2.2nd.Edition.Dec.2005.eBook-DDU",
	"Que.Developing.And.Implementing.Web.Applications.With.Visual.C.Sharp.Dot.NET.And.Visual.Studio.Do",
	"Que.Special.Edition.Using.Enterprise.JavaBeans.2.0.internal.eBook-LiB",
	"Que.Special.Edition.Using.Java.2.Standard.Edition.internal.eBook-LiB",
	"QuickTime For Java - A Developer's Notebook (2005)",
	"Rails For Java Developers (2007)",
	"Rails Solutions - Ruby On Rails Made Easy (2007)",
	"Rampant.Tech.Press.Oracle.Index.Management.Secrets.Top.Oracle.Experts.Discuss.Index.Management.Tech",
	"Rampant.Tech.Press.Using.the.Oracle.oradebug.Utility.Debugging.Oracle.Applications.eBook-DDU",
	"Rampant.TechPress.Advanced.SQL.Database.Programmers.Handbook",
	"Rampant.TechPress.Documenting.Oracle.Databases.Complete.Oracle.Database.Schema.Auditing.eBook-TLFeB",
	"Rampant.TechPress.Oracle.DBA.Made.Simple.Oracle.Database.Administration.Techniques.eBook-DDU",
	"Rampant.TechPress.Oracle.Data.Warehouse.Management.eBook-DDU",
	"Rampant.TechPress.Oracle.SQL.Internals.Handbook",
	"Rampant.TechPress.Oracle.Space.Management.Handbook.eBook-DDU",
	"Rampant.TechPress.Using.Oracle.SQL.Stored.Outlines.and.Optimizer.Plan.Stability.eBook-DDU",
	"Real 802.11 Security - Wi-Fi Protected Access And 802.11i (2003)",
	"Rootkits - Subverting the Windows Kernel",
	"Syngress - Hack Proofing Sun Solaris 8",
	"Syngress - Wireless Hacking. Projects for Wi-Fi Enthusiasts",
	"The Art Of Intrusion - The Real Stories Behind The Exploits Of Hackers, Intruders, And Deceivers",
	"The Complete History of Hacking",
	"Ubuntu Hacks - Tips and Tools For Exploring, Using, And Tuning Linux (2006)",
	"Wi-Foo - The Secrets Of Wireless Hacking (2004)",
	"Wiley.Hacking.Knoppix.Jan.2006",
	"Windows Server Hacks (2004)",
	"Windows XP Hacks - Tips and Tools For Optimizing Your OS, 2nd Edition (2005)",
	"Windows XP Hacks and Mods for Dummies",
	"Wireless Hacks - 100 Industrial-Strength Tips and Tools (2003)",
	"Wireless Network Hacks and Mods for Dummies",
	"XML Hacks - 100 Industrial-Strength Tips and Tools (2004)",
	"decrypted-secrets-methods-and-maxims-of-cryptology.9783540245025.27381",
	"disc_tumbler_handle_locks_11-04",
	"disc_tumbler_overview",
	"do-it-yourself-pick-case-making",
	"e-book_-cia-_-lock-picking-field-operative-training-manual",
	"eBook.McGraw.Hill.Osborne.Oracle.Database.10g.SQL",
	"eMbedded Visual Basic Windows CE and Pocket PC Mobile Applications 2002",
	"impressioning-manual-for-amateur-locksmiths",
	"java precisely",
	"javascript bible 4th edition + jsb gold chapters",
	"java threads 2nd edition",
	"john.wiley.sons.wiley.wi.fi.toys.15.cool.wireless.projects.for.home.office.and.entertainment.oct",
	"john wiley and sons - adobe illustrator cs for dummies",
	"john wiley and sons - adobe photoshop cs in 10 simple steps or less",
	"john wiley and sons - dreamweaver mx 2004 bible",
	"john wiley and sons - ethernet networks. design, implementation, operation, management. 4th edition",
	"john wiley and sons - photoshop cs all-in-one desk reference for dummies",
	"linux+ certification bible",
	"linux - Advanced Bash Shell Scripting Guide",
	"linux.device.drivers.3rd.edition.feb.2005.ebook-ddu",
	"linux programming unleashed",
	"lockpicking-homemade-clicker",
	"lockpicking-jiggle-keys",
	"locksmith-safe-crack-guide-to-manipulation",
	"lsiguide",
	"manning - java development with ant",
	"mcgraw-hill - ccsp - cisco certified security professional certification all-in-one exam guide",
	"mcgraw-hill - citrix metaframe for windows server 2003. the official guide",
	"mcgraw-hill - iis 6 the complete reference",
	"mcgraw-hill - perl. the complete reference. second edition",
	"mcgraw-hill - wi-fi handbook. building 802.11b wireless networks",
	"mcgraw-hill - wi-fi security",
	"mcgraw-hill - windows server 2003. best practices for enterprise deployments",
	"mcgraw-hill - windows server 2003 clustering and load balancing",
	"mcgraw-hill - windows server 2003 pocket administrator",
	"microsoft press - microsoft windows server 2003 terminal services",
	"microsoft sql server 2000 weekend crash course",
	"mit press - beowulf cluster computing with linux, second edition",
	"o'reilly - building embedded linux systems",
	"o'reilly - building secure servers with linux",
	"o'reilly - building wireless community networks, second edition",
	"o'reilly - cisco cookbook",
	"o'reilly - cisco ios access lists",
	"o'reilly - content syndication with rss",
	"o'reilly - flash remoting. the definitive guide",
	"o'reilly - html and xhtml. the definitive guide, 5th edition",
	"o'reilly - java and soap",
	"o'reilly - java data objects",
	"o'reilly - java extreme programming cookbook",
	"o'reilly - java performance tuning. second edition",
	"o'reilly - java script and dhtml cookbook",
	"o'reilly - javaserver pages. - 2nd edition",
	"o'reilly - java web services in a nutshell",
	"o'reilly - learning perl objects, references and modules",
	"o'reilly - learning red hat enterprise linux and fedora, 4th edition",
	"o'reilly - learning red hat linux, 3rd edition",
	"o'reilly - learning xml, second edition",
	"o'reilly - linux in a nutshell, 4th edition",
	"o'reilly - linux security cookbook",
	"o'reilly - macosx for java geeks",
	"o'reilly - mac os x unwired",
	"o'reilly - mysql pocket reference",
	"o'reilly - network security assessment",
	"o'reilly - network security hacks",
	"o'reilly - oracle pl.sql language pocket reference, 2nd edition",
	"o'reilly - perl 6 essentials",
	"o'reilly - perl and xml",
	"o'reilly - perl cookbook, second edition",
	"o'reilly - practical mod_perl",
	"o'reilly - practical unix and internet security, 3rd edition",
	"o'reilly - tcpip network administration. 3rd edition",
	"o'reilly - understanding the linux kernel",
	"o'reilly - upgrading to php 5",
	"o'reilly - web database applications with php and mysql, second edition",
	"o'reilly - xml hacks. 100 industrial-strength tips and tools",
	"o'reilly - xml in a nutshell. second edition",
	"oracle press. oracle 9i - the complete reference",
	"oreilly.php.hacks.tips.and.tools.for.creating.dynamic.websites.dec.2005.happy.new.year",
	"oreilly.running.linux.5th.edition.dec.2005",
	"oreilly.wireless.hacks.ebook_lib",
	"paraglyph publishing - jeff duntemann's drive-by wi-fi guide",
	"peachpit press - macromedia flash mx 2004 actionscript. training from the source",
	"peachpit press - microsoft windows xp.visual quickstart guide",
	"perl in a nutshell - o'reilly [ebook, programming]",
	"premier press - microsoft windows xp professional administrator's guide",
	"premier press - php.mysql programming for the absolute beginner",
	"prentice.hall.an.introduction.to.programming.using.visual.basic.2005.6th.edition.mar.2006",
	"prentice.hall.introduction.to.computing.and.programming.with.java.a.multimedia.approach.apr.2006",
	"prentice hall - ip in wireless networks",
	"prentice hall ptr - a field guide to wireless lan's for administrators and power users",
	"prentice hall ptr - core php programming, third edition",
	"prentice hall ptr - home networking basis",
	"prentice hall ptr - how secure is your wireless network",
	"prentice hall ptr - java for coldfusion developers",
	"prentice hall ptr - linux on the mainframe",
	"prentice hall ptr - unix systems programming, second edition",
	"prentice hall ptr - wireless communication systems",
	"programming - xml b",
]
